from flask_login import UserMixin, current_user
from datetime import datetime 
from application import db, login_manager#, admin, ModelView


# admin.add_view(ModelView(User, db.session))
        

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(db.Model,UserMixin):
    id = db.Column(db.Integer, primary_key=True) 
    email = db.Column(db.String(80), unique=True, nullable=False) 
    password = db.Column(db.String(255), nullable=False)
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))
    phone_number = db.Column(db.String(50))
    confirmed_email = db.Column(db.Boolean, default=False)
    suspended = db.Column(db.Boolean, default=False)
    num_of_times_suspended = db.Column(db.Integer, default=0)
    reg_date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    country = db.Column(db.String(40))
    ip = db.Column(db.String(20))


class Order(db.Model):       
    id = db.Column(db.Integer, primary_key=True) 
    product = db.Column(db.String(60), db.ForeignKey('phones.id'))
    delivered = db.Column(db.Boolean, default=False)
    date_delivered = db.Column(db.DateTime)
    date_ordered = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

class Cart(db.Model):       
    id = db.Column(db.Integer, primary_key=True) 
    user_id = db.Column(db.String(60), db.ForeignKey('user.id'))
    product = db.Column(db.String(60), db.ForeignKey('phones.id'))
    date_carted= db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class Phones(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date_added = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    # details = db.Column(db.PickleType, default={})
    brand = db.Column(db.String(40))
    year = db.Column(db.String(10))
    availability = db.Column(db.String(40))
    price = db.Column(db.String(20))
    network_2g = db.Column(db.String(40))
    network_3g = db.Column(db.String(40))
    network_4g = db.Column(db.String(40))
    network_5g = db.Column(db.String(40))
    sim_size = db.Column(db.String(40))
    sim_multiple = db.Column(db.String(40))
    body_form_factor = db.Column(db.String(40))
    body_keyboard = db.Column(db.String(40))
    body_height = db.Column(db.String(40))
    body_width = db.Column(db.String(40))
    body_weight = db.Column(db.String(40))
    body_thickness = db.Column(db.String(40))
    body_ip_certificate = db.Column(db.String(40))
    body_color = db.Column(db.String(40))
    body_back_material = db.Column(db.String(40))
    body_frame_material = db.Column(db.String(40))
    os = db.Column(db.String(40))
    os_version = db.Column(db.String(40))
    cpu_freq = db.Column(db.String(40))
    cpu_cores = db.Column(db.Integer)
    chipset = db.Column(db.String(40))
    ram = db.Column(db.String(40))
    storage = db.Column(db.String(40))
    card_slot = db.Column(db.String(40))
    display_resolution = db.Column(db.String(40))
    display_size = db.Column(db.String(40))
    display_density = db.Column(db.String(40))
    display_technology = db.Column(db.String(40))
    display_notch = db.Column(db.String(40))
    display_high_refresh_rate = db.Column(db.Boolean)
    display_hdr = db.Column(db.Boolean)
    main_camera_resolution = db.Column(db.String(40))
    main_camera_f_number = db.Column(db.String(40))
    main_camera_cameras = db.Column(db.String(40))
    main_camera_ois = db.Column(db.Boolean)
    main_camera_telephoto = db.Column(db.Boolean)
    main_camera_ultrawide = db.Column(db.Boolean)
    main_camera_flash = db.Column(db.Boolean)
    main_camera_video = db.Column(db.String(40))
    selfie_camera_resolution = db.Column(db.String(40))
    selfie_camera_dual_camera = db.Column(db.Boolean)
    selfie_camera_ois = db.Column(db.Boolean)
    selfie_camera_front_flask = db.Column(db.Boolean)
    selfie_camera_pop_up_camera = db.Column(db.Boolean)
    selfie_camera_under_display = db.Column(db.Boolean)
    sensor_accelerometer = db.Column(db.Boolean)
    sensor_compass = db.Column(db.Boolean)
    sensor_gyro = db.Column(db.Boolean)
    sensor_compass = db.Column(db.Boolean)
    sensor_proximity = db.Column(db.Boolean)
    sensor_heart_rate = db.Column(db.Boolean)
    sensor_fingerprint = db.Column(db.String(40))
    wlan = db.Column(db.String(40))
    bluetooth = db.Column(db.String(40))
    gps = db.Column(db.Boolean)
    nfc = db.Column(db.Boolean)
    infrared = db.Column(db.Boolean)
    fm_radio = db.Column(db.Boolean)
    usb_type_c = db.Column(db.Boolean)
    battery_capacity = db.Column(db.String(40))
    battery_removable = db.Column(db.String(40))
    charging_wired = db.Column(db.String(40))
    charging_wireless = db.Column(db.String(40))
    misc_free_text = db.Column(db.String(40))
    misc_order = db.Column(db.String(40))
    misc_reviewed_only = db.Column(db.Boolean)
    new = db.Column(db.Boolean)
    description = db.Column(db.String(1000)) # to be added
    phone_image = db.Column(db.String(1024)) # to be added
    name = db.Column(db.String(300)) # to be added





class Userfilter(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.String(60), db.ForeignKey('user.id'))
    date_made = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    ordered = db.Column(db.String(60), db.ForeignKey('phones.id')) #to be change to oder.id from phones.id
    brand = db.Column(db.String(40))
    year = db.Column(db.String(10))
    availability = db.Column(db.String(40))
    price = db.Column(db.String(20))
    network_2g = db.Column(db.String(40))
    network_3g = db.Column(db.String(40))
    network_4g = db.Column(db.String(40))
    network_5g = db.Column(db.String(40))
    sim_size = db.Column(db.String(40))
    sim_multiple = db.Column(db.String(40))
    body_form_factor = db.Column(db.String(40))
    body_keyboard = db.Column(db.String(40))
    body_height = db.Column(db.String(40))
    body_width = db.Column(db.String(40))
    body_weight = db.Column(db.String(40))
    body_thickness = db.Column(db.String(40))
    body_ip_certificate = db.Column(db.String(40))
    body_color = db.Column(db.String(40))
    body_back_material = db.Column(db.String(40))
    body_frame_material = db.Column(db.String(40))
    os = db.Column(db.String(40))
    os_version = db.Column(db.String(40))
    cpu_freq = db.Column(db.String(40))
    cpu_cores = db.Column(db.Integer)
    chipset = db.Column(db.String(40))
    ram = db.Column(db.String(40))
    storage = db.Column(db.String(40))
    card_slot = db.Column(db.String(40))
    display_resolution = db.Column(db.String(40))
    display_size = db.Column(db.String(40))
    display_density = db.Column(db.String(40))
    display_technology = db.Column(db.String(40))
    display_notch = db.Column(db.String(40))
    display_high_refresh_rate = db.Column(db.Boolean)
    display_hdr = db.Column(db.Boolean)
    main_camera_resolution = db.Column(db.String(40))
    main_camera_f_number = db.Column(db.String(40))
    main_camera_cameras = db.Column(db.String(40))
    main_camera_ois = db.Column(db.Boolean)
    main_camera_telephoto = db.Column(db.Boolean)
    main_camera_ultrawide = db.Column(db.Boolean)
    main_camera_flash = db.Column(db.Boolean)
    main_camera_video = db.Column(db.String(40))
    selfie_camera_resolution = db.Column(db.String(40))
    selfie_camera_dual_camera = db.Column(db.Boolean)
    selfie_camera_ois = db.Column(db.Boolean)
    selfie_camera_front_flask = db.Column(db.Boolean)
    selfie_camera_pop_up_camera = db.Column(db.Boolean)
    selfie_camera_under_display = db.Column(db.Boolean)
    sensor_accelerometer = db.Column(db.Boolean)
    sensor_compass = db.Column(db.Boolean)
    sensor_gyro = db.Column(db.Boolean)
    sensor_compass = db.Column(db.Boolean)
    sensor_proximity = db.Column(db.Boolean)
    sensor_heart_rate = db.Column(db.Boolean)
    sensor_fingerprint = db.Column(db.String(40))
    wlan = db.Column(db.String(40))
    bluetooth = db.Column(db.String(40))
    gps = db.Column(db.Boolean)
    nfc = db.Column(db.Boolean)
    infrared = db.Column(db.Boolean)
    fm_radio = db.Column(db.Boolean)
    usb_type_c = db.Column(db.Boolean)
    battery_capacity = db.Column(db.String(40))
    battery_removable = db.Column(db.String(40))
    charging_wired = db.Column(db.String(40))
    charging_wireless = db.Column(db.String(40))
    misc_free_text = db.Column(db.String(40))
    misc_order = db.Column(db.String(40))
    misc_reviewed_only = db.Column(db.Boolean)
    new = db.Column(db.Boolean)




